version: "3.8"
services:
    nginx:
        command: nginx -g "daemon off;"
        build:
            context: .
            dockerfile: ./docker/Dockerfile.nginx
        volumes:
            - ./docker/nginx.conf:/etc/nginx/nginx.conf
            - logs:/var/log/nginx
    echo:
        image: jmalloc/echo-server:v0.3.7
    test_e2e:
        build:
            context: .
            dockerfile: ./docker/Dockerfile.e2e
        environment:
            - ENDPOINT=nginx
            - LOG_FILE_PATH=/var/log/nginx/ws.log
        volumes:
            - logs:/var/log/nginx
        depends_on:
            - nginx
            - echo
    test:
        build:
            context: .
            dockerfile: ./docker/Dockerfile.unit

volumes:
    logs:
